### ISSUE TITLE
Please add tab icons

### ISSUE THREAD

**Issue by victornpb** [wyze/atom-seti-icons#39]
This is the best icon set, I just miss icons on the tabs.

**Comment by wyze** [comment]
There are icons on the tabs. Which theme are you using?

**Comment by UltCombo** [comment]
Confirmed, no tab icons in One Dark UI theme.

**Comment by UltCombo** [comment]
Oh, the problem is with One Dark's "Tab Sizing" config set to "Minimum" (or "Auto" with a small window).

I've fixed the problem adding this to stylesheet:

```css
[theme-one-dark-ui-tabsizing="minimum"] .tab-bar .tab .title::before {
  position: static;
  margin-top: 0;
  margin-left: 0;
  display: inline-block;
  vertical-align: middle;
}
```

I believe it is also possible to fix this by just adding a `padding-left` value to the `.tab title`, but seeing as the icons' width are not always the same, it seems hacky to do so and very hard to find a value that looks properly centered with the various icons (i.e. visually the same padding in the left and right sides of the tab title).
