### ISSUE TITLE
[Suggestion] A little tweak for the package

### ISSUE THREAD

**Issue by starman-vlad** [wyze/atom-seti-icons#73]
Hi,

It started to annoy me that icons have unnecessary `margin` and `padding` so I tweaked them to look like this:

![my_code](https://user-images.githubusercontent.com/12301022/30523430-64230594-9be1-11e7-9486-e992fec80943.png)

Code that I tweaked in `styles.less` 
```css
.list-tree.has-collapsable-children .list-nested-item.collapsed > .list-item::before {
    left: 15px !important;
}
atom-workspace.theme-atom-material-ui .icon-file-directory::before {
    margin-right: 4px !important;
}
atom-workspace .entries.list-tree .file .icon::before {
    font-size: 26px;
    right: -16px;
    top: 9px !important;
}
.list-tree.has-collapsable-children li.list-item {
    padding: 0 !important;
    margin: 0 !important;
}
```

But your code looks like this:

![pkg_code](https://user-images.githubusercontent.com/12301022/30523374-9cdf6af4-9be0-11e7-8494-5cd1cc2eeece.png)

My resolution is `1366x768` and your current style has very small icons and big spacing. 
Would you consider on tweaking these bad boys a bit?
